[workspace]
members = [
    "hermes",
    "hermes-ffi",
    "hermes-ffi-test",
    "hermes-inprocess",
    "hermes-mqtt",
    "hermes-mqtt-ffi",
    "hermes-test-suite",
    "hermes-utils",
    "hermes-utils-derive",
]
