[package]
name = "hermes-utils"
version = "0.1.0"
authors = ["Thibaut Lorrain <thibaut.lorrain@snips.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hermes-utils-derive = { path="../hermes-utils-derive" }
